Repository nugu-developers/nugu-android, pull requests merged in 2019-12, with the labels that each got.

#112 Fix leak at inputProcessorManager (#111)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/inputprocessor/InputProcessorManagerInterface.kt
Labels: bug

#113 Update external library
  versions.gradle
Labels: bug

#117 Return value for sendMessage
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageSender.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/Transport.kt
Labels: enhancement

#121 Improve shared circulr buffer's thread wait (#119)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/sds/CircularBufferSharedDataStream.kt
Labels: enhancement

#122 Fix missing call for reader's close (#120)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#126 intial CHANGELOG (#110)
  CHANGELOG.md
Labels: documentation

#132 Rename payload for handoffConnection (#131)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSystemAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/connection/ConnectionManagerInterface.kt
Labels: enhancement

#136 Set default value
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayInterface.kt
Labels: enhancement

#138 Update silverTray to v4.1.8 (#137)
  versions.gradle
Labels: bug

#140 Return id for setElementSelected's request (#139)
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/client/DisplayAggregator.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/BaseDisplayAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/common/EventCallback.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/display/DisplayInterface.kt
Labels: enhancement

#148 Mapping errors using ChangedReason (#147)
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/res/values/strings.xml
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
Labels: bug, enhancement

#153 Fix startListening not work (#152)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#155 Fix invalid transit to IDLE state (#154)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogUXStateAggregator.kt
Labels: bug

#158 Fix invalid opus player status change (#157)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
Labels: bug
