Repository nugu-developers/nugu-android, pull requests merged in 2020-07, with the labels that each got.

#864 Allow nullable field of volume context (#863)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
Labels: new

#870 Update Person object (#865)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
Labels: improve

#872 Grpc not initialized before sending message (#871)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
Labels: fix

#875 Support Speaker Interface v1.2 (#874)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
Labels: new

#878 Apply blocking policy at Chips.Render (#877)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/handler/RenderDirectiveHandler.kt
Labels: improve

#882 Rename shuffle/favorite/repeat API (#881)
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
Labels: fix

#884 Update keensense v0.2.2 (#883)
  versions.gradle
Labels: improve

#887 Change API of MessageClient (#885)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
Labels: improve

#876 Fix incorrect state processing (v1)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
Labels: fix

#890 Fix reverse order of playstack (#889)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/context/PlayStackContextManagerTest.kt
Labels: bug

#894 Fix not resume audioPlayer on foreground (#893)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#892 Allow nullable location (#891)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/location/LocationProvider.kt
Labels: improve

#896 Apply blocking policy for MakeCall directive(#895)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/MakeCallDirectiveHandler.kt
Labels: improve

#898 Fix wrong acquire channel (#897)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSScenarioPlayer.kt
Labels: fix

#900 PhoneCall.CandidatesListed with full context (#880)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
Labels: improve

#901 Update NuguServiceKit
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsAgreementActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_webview.xml
  app/src/main/res/values/strings.xml
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/Const.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/WebViewUtils.kt
Labels: improve

#903 Fix according to UX guide
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
  app/src/main/res/layout/bottom_sheet_voice_window.xml
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/EllipsizeTextView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguButton.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguToast.kt
  nugu-ux-kit/src/main/res/layout/item_text.xml
Labels: fix

#905 Fix not stop listening on working (#904)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: fix

#910 Open connection manager interface (#909)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
Labels: improve

#908 Notify when dialogMode changed (#907)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#911 Fix build error
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
Labels: fix

#913 Add debug log for chips
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
Labels: improve

#919 Add the ResetConnection and Noop directive
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouterInterface.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/connection/ConnectionManagerInterface.kt
Labels: fix

#923 Notify the chips for a recent session (#922)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: bug

#924 Feature/issue 841
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
Labels: improve

#929 Apply review(UX)
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
  app/src/main/res/layout/bottom_sheet_voice_window.xml
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/EllipsizeTextView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/EllipsizedTextView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
  nugu-ux-kit/src/main/res/layout/item_text.xml
Labels: fix

#934 Fix incorrect if expression
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/ResponseHandler.kt
Labels: fix

#932 Fix wrong directive name (#931)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallClient.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/BlockIncomingCallDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/BlockIncomingCallPayload.kt
Labels: fix

#935 Update the policy of the playSync (#914)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
Labels: new

#938 Publish getAgent() through a NuguAndroidClient (#937)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClientInterface.kt
Labels: improve

#945 Update SilverTray v4.2.2 (#944)
  versions.gradle
Labels: improve

#949 Fix wrong release request (#948)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
Labels: fix

#951 Send a valid playServiceId (#950)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#946 Feature/issue 942
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
Labels: fix

#953 Do not stop AudioPlayer if not immediately (#948)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#955 Fix invalid playContext when tts finished (#954)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSPlayContextProvider.kt
Labels: fix

#958 Fix BT streaming & focus issue (#939)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
Labels: improve

#964 Add some debug log
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
Labels: enhancement

#957 Improve tts's focus release logic (#936)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: improve

#959 Test PlaySynchronizer
  nugu-core/src/test/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizerTest.kt
Labels: test

#960 Fix failed test
  nugu-agent/src/test/java/com/nugu/sdk/agent/playbackcontrol/PlaybackControllerTest.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
Labels: test

#966 Fix invalid asr result (#965)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: fix

#962 Fix missing parameter when creating Intent of AccountInfo
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: fix

#969 Fix invalid outdate event handling (#968)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: fix

#978 Deactivate session at expectSpeech finished (#977)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#974 Improve focus managing with external focus (#973)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
Labels: improve

#981 Apply url compare logic for resume (#980)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: improve

#988 Add callback to notify request is created (#987)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
Labels: improve

#990 Add missing notify (#987)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
Labels: fix

#992 Manage focus for PhoneCall (#989)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
Labels: improve

#963 Add KeepConnection to change during runtime (#952)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransportFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransportFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/NuguServerInfo.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2TransportFactory.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/NuguServerInfo.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouterInterface.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/connection/ConnectionManagerInterface.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/TransportFactory.kt
Labels: improve

#997 Fix invalid getCurrentChips (#996)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#995 Simplify dialogUX notify logic (#994)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: improve

#1000 Fix not release focus when tts finish/stop (#999)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1004 Send CallArrived event with full context (#1003)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
Labels: improve

#1007 Fix issue where sometimes the connection is unexpectedly disconnected
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/DeviceGatewayClient.kt
Labels: fix

#1009 Update webview interface to handle withdrawn user (#1008)
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsAgreementActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1011 Fixed issue where epd does not stop #1010
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: fix

#1016 Fix read's return correctly after close #1015
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/sds/CircularBufferSharedDataStream.kt
Labels: fix

#1013 Update the priority of focus #1012
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/Channel.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/ChannelTest.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizerTest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
Labels: improve

#1018 Synchronize ASR.ExpectSpeech as Play #1017
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
Labels: improve

#1023 Provide session at onDialogUXStateChanged #1022
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregatorInterface.kt
Labels: improve

#1014 Add feature noAck at Call (#1006)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Call.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Status.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/FixedStateCall.kt
Labels: fix

#1027 Add a call to shutdown() on scheduler of Transport (#1026)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Transport.kt
Labels: fix
