Repository nugu-developers/nugu-android, pull requests merged in 2020-03, with the labels that each got.

#355 Fix typo
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: bug

#357 Fix screen's context not updated (#356)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#360 Add listener for received directives (#359)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveGroupProcessorInterface.kt
Labels: enhancement

#362 Add OnSendMessageListener (#361)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageSender.kt
Labels: enhancement

#366 Add handler for text source directive (#365)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#370 Add onStop at OnPlaybackListener (#369)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt
Labels: enhancement

#375 Fix not stopped audio player after finished (#374)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#380 Fix audio player not playing for URL (#379)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#385 Fix tts player not work using two or more (#384)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
Labels: bug

#388 Send referrerDialogRequestId on event
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
Labels: bug

#394 Apply observer to gather play context (#393)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt
Labels: enhancement

#390 Add callback for request (#383)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Labels: enhancement

#389 Feature/issue 384
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
Labels: enhancement

#396 Add missing copryright
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayTimer.kt
Labels: documentation

#405 Fix expectSpeechPayload not included at ListenXXX event (#404)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#409 Fix close directive not completed (#408)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: bug

#403 Remove second awaitTermination
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/ChannelBuilderUtils.kt
Labels: bug

#412 Add System.Revoke directive
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/SystemAgentInterface.kt
Labels: enhancement

#411 Fix start recognition called twice (#410)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#418 Fix overflow issue (#417)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
Labels: bug

#419 Apply review (#417)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
Labels: bug

#414 Add dialogRequestId at action (#413)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/extension/ExtensionAgentInterface.kt
Labels: enhancement

#421 Apply review
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
Labels: bug

#425 Add missing return for requestTTS (#424)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Labels: bug, enhancement

#422 Add event listener for text source handler (#420)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
Labels: enhancement

#428 Apply contextLayer for Display (#427)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/delegation/DelegationClient.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: enhancement

#429 Enable audio player v1.2 (#373)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#431 Apply defaultVolumeStep for Speaker (#430)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
Labels: enhancement

#434 Fix not working previous command (#433)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#436 Fix wrong state value at Screen's context (#435)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
Labels: bug

#447 Append dialogRequestId at Context (#446)
  app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
Labels: enhancement

#448 Fix crash
  app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
Labels: bug

#450 Strictly check token for render directives (#449)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: enhancement

#454 Extract time from UUID (#453)
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
Labels: enhancement

#455 Manage sourceId for IntegratedMediaPlayer (#442)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/IntegratedMediaPlayer.kt
Labels: bug, enhancement

#465 Add flag for enable or disable of Display (#460)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#464 Fix opus player's offset (#463)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
Labels: bug

#462 Fix forward scenario not working (#461)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#459 Manage playStack using timestamp (#458)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt
Labels: enhancement

#469 Fix DM not working
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#472 Stop player when request stop by agent (#471)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#484 Remove field('property') at ExpectSpeech (#483)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogSessionManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/dialog/DialogSessionManagerInterface.kt
Labels: enhancement

#478 Add missing RDRID
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#482 Fix missing token for TTS's playback event (#481)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug

#474 Allow to use w.o KeywordDetector (#473)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: enhancement

#486 Prevent start epd when already started (#485)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: bug

#488 Prevent DM from being closed by wakeup (#487)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#489 Bugfix/issue 487
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#496 Allow empty token for display (#495)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
Labels: enhancement

#499 Update silvertray v4.1.12 (#497)
  versions.gradle
Labels: enhancement

#494 Fix display context missed (#493)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#492 Fix player not resume after explicit paused(#491)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#506 Bugfix/issue 432 (#432)
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: bug

#505 Remove address in serverPolicies
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/Options.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/ChannelBuilderUtils.kt
Labels: enhancement

#502 Fix crash sample app (#501)
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/view/DisplayAudioPlayer.kt
  app/src/main/res/layout/view_display_audioplayer.xml
Labels: bug

#500 Apply update for AudioPlayer display (#490)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: enhancement

#504 Disable connectionPool
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
Labels: bug

#508 Support FullText3 for display (#507)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
Labels: enhancement

#510 Update silverTray v4.1.13
  versions.gradle
Labels: enhancement

#512 Nullable playServiceId for requestTTS (#511)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Labels: enhancement

#517 Apply asrContext payload (#516)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/dialog/DialogSessionManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/dialog/DialogSessionManagerInterface.kt
Labels: enhancement

#519 Handle tts error correctly (#518)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt
Labels: bug

#521 Fix not stopped for already fetched item (#520)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#523 Add render failed notify (#522)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayInterface.kt
Labels: enhancement

#525 Improve parsing of policy
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/Options.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/Policy.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/PingService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/ChannelBuilderUtils.kt
  nugu-client-kit/src/main/proto/registry.proto
Labels: enhancement

#527 Apply RDRID at Request{XXX}event (#526)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlayCommandDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
Labels: enhancement

#530 Prevent release focus when prepare playing (#529)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug

#531 Fix onceLoginListner to be null before executing callback
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: bug, enhancement

#533 Back to idle state only request failed (#532)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#536 Add playServiceId comparison (#535)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#540 Stop audio player when loss focus always (#539)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#538 ActiveTransport is Nulled in MessageRouter
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
Labels: bug

#547 Send power of wakeup (#546)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/PayloadWakeup.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: enhancement

#548 Apply CancelRecognize directive (#545)
  app/src/main/java/com/skt/nugu/sampleapp/widget/BottomSheetController.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/CancelRecognizeDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#551 Apply new context policy (#550)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: enhancement
