Repository nugu-developers/nugu-android, pull requests merged in 2020-05, with the labels that each got.

#680 Handle fetch failure correctly
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#682 Fix wrong referrerDialogRequestId (#681)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#685 Fix wrong templateId's update call (#684)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: bug

#689 Create messageId after dialogRequestId (#688)
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/EventMessageRequest.kt
Labels: enhancement

#691 Remove intent flag when starting NuguOAuthCallbackActivity
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: bug

#693 Fix wrong animation duration
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguButton.kt
Labels: bug

#692 Associate directive and source id
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: enhancement

#694 Handle ExpectSpeech canceling (#690)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug, enhancement

#700 Fix inproper focus release (#699)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#704 Ensure execution order for FocusManager (#703)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
Labels: bug, enhancement

#715 Apply timeout for attachment (#714)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/AttachmentManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/attachment/AttachmentManagerInterface.kt
Labels: enhancement

#725 Fix tts not playing
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug

#724 Add WITHDRAWN_USER reason at System.Revoke (#723)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/SystemAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/handler/RevokeDirectiveHandler.kt
Labels: enhancement

#722 Cancel a item fetched but not playing yet (#721)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#735 Fix wrong payload
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
Labels: bug

#732 Fix incorrect state processing
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcTransport.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Transport.kt
Labels: bug

#738 Update keensense v0.2.1
  versions.gradle
Labels: enhancement

#741 Fix wrong merge
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/MessageRequestConverter.kt
Labels: bug, enhancement

#739 Remove SynchronizeState event from CONNECTED state #734
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
Labels: enhancement

#740 Improve grpc stream management
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventsService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/PingService.kt
Labels: enhancement
