Repository nugu-developers/nugu-android, pull requests merged in 2020-12, with the labels that each got.

#1445 Update SampleAPP to set more detailed URL scheme #1444
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
Labels: improve

#1447 Fix Utility.Block's blocking policy #1446
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/utility/handler/BlockDirectiveHandler.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/BlockingPolicy.kt
Labels: fix

#1442 Add missing new backoff logic to http2 #1349
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/DeviceGatewayClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/EventsService.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/PingService.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/utils/BackOff.kt
Labels: fix

#1449 Support AudioPlayer v1.5 #1448
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: new

#1453 Call missing callback #1452
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: fix

#1455 Deactivate session when ExpectSpeech failed #1454
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1457 Fix threading issue for getOffset() #1456
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
Labels: fix

#1465 Apply sdk version 29 for build #1464
  app/build.gradle
  nugu-android-helper/build.gradle
  nugu-login-kit/build.gradle
  nugu-service-kit/build.gradle
  nugu-ux-kit/build.gradle
  versions.gradle
Labels: improve

#1462 Apply interaction control at ControlScroll #1460
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlScrollDirectiveHandler.kt
Labels: new

#1467 Update SilverTray v4.3.2 #1466
  versions.gradle
Labels: fix

#1473 Fix type mismatch error
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/utils/PackageUtils.kt
Labels: fix

#1471 Fix screen orientation in oauth login
  nugu-login-kit/src/main/AndroidManifest.xml
Labels: fix

#1476 Only compare token for Stop,Continue #1475
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: fix

#1478 Update SilverTray v4.3.3 #1477
  versions.gradle
Labels: improve

#1483 Fix ExoMediaPlayer doesn't calling onRetrieved callback
  app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
Labels: bug

#1486 Deliver template json on update AudioPlayer #1485
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: improve

#1480 fix "Only fullscreen opaque activities can request orientation" issue
  nugu-login-kit/src/main/AndroidManifest.xml
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
Labels: fix

#1489 Clear lastStopped when new directive handled #1488
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1491 Add call to onPostSendMessage when sending AttachmentMessage #1490
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
Labels: fix

#1494 Feature/issue 1492
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1496 Pause routine if cancel or failed #1495
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/DirectiveGroupHandlingListener.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: improve
