Repository nugu-developers/nugu-android, pull requests merged in 2020-02, with the labels that each got.

#235 Setup snapshot setting (#234)
  publish-android.gradle
  publish.gradle
  versions.gradle
Labels: enhancement

#239 Apply battery charing status (#238)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/BatteryStatusProvider.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/battery/AndroidBatteryStatusProvider.kt
Labels: enhancement

#243 Prototype screen interface v1.0 (#242)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/screen/AbstractScreenAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/screen/Screen.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/ScreenAgentFactory.kt
Labels: enhancement

#247 Update SilverTray v4.1.9 (#246)
  versions.gradle
Labels: bug

#252 Add mediaType at AttachmentMessage (#251)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageInterpreter.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/AttachmentMessage.kt
Labels: enhancement

#256 Fix a issue where the TimeUUID v2 spec does not apply (#172)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/EventMessageRequest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
Labels: bug

#261 Remove light agent impl (#260)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultLightAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/light/AbstractLightAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/light/Light.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/LightAgentFactory.kt
Labels: enhancement

#264 Apply duration of display payload (#263)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: bug

#259 Fix pause not work (#258)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
Labels: bug

#265 Revert #258 partially.
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
Labels: bug

#269 Play attahcment at AudioPlayerAgent (#236)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioItem.kt
Labels: enhancement

#268 Deliver display type correctly (#267)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveGroupProcessorInterface.kt
Labels: enhancement

#273 Handle notify result error (#272)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: bug, enhancement

#271 Handle AudioPlayer.Stop directive on finish (#270)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#276 Divide display control API (#275)
  app/src/main/java/com/skt/nugu/sampleapp/template/FragmentTemplateRenderer.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerDisplayInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayInterface.kt
Labels: enhancement

#278 Do not send pcm & boundary on client EPD (277)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: enhancement

#283 Allow to control epd params per request (#282)
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AbstractASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/EndPointDetectorParam.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/audio/AudioEndPointDetector.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/jademarble/EndPointDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
Labels: enhancement

#287 Attach missed payload at request (#286)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/delegation/DelegationAgentInterface.kt
Labels: bug, documentation

#289 Fix audio player not working (#288)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioItem.kt
Labels: bug

#294 Handle speaker directive as blocking (#293)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
Labels: enhancement

#291 Fix incorrect delivery of hasPairedDevices
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothEventBus.kt
Labels: bug

#292 Add poc status in oAuthClient (#248)
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
  app/src/main/res/values/strings.xml
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/UnAuthenticatedException.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/exception/BaseException.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/net/HttpClient.kt
Labels: enhancement

#290 Fix not play after animation stop (#209)
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
Labels: bug

#304 Apply rate params at setVolume (#303)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
Labels: bug

#302 Send event with current context (#301)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#300 Bugfix/issue 298
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: bug, enhancement

#299 Feature/issue 297
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: documentation, enhancement

#307 Remove movement interface (#306)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMovementAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/movement/AbstractMovementAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/movement/MovementController.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/MovementAgentFactory.kt
Labels: enhancement

#308 Pass all directives to input processor on receive
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/inputprocessor/InputProcessor.kt
Labels: enhancement

#311 Handle complete for setMute directive (#310)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
Labels: bug

#312 Fix an error when the stream was closed (#309)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
Labels: bug

#314 Fix data field type (#313)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/metadata/AudioPlayerMetadataDirectiveHandler.kt
Labels: bug

#318 Fix voice chrome not dismissed (#317)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: bug

#321 Fix audioplayer stopped after 10s pausing (#320)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#323 Fix wrong event name for setVolume/setMute (#322)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
Labels: bug

#324 Fix wrong resume issue on focus change (#266)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#325 Send pause event correctly (#297)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#328 Use delay to prevent resume audio player (#266)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#330 Fix missing permissions required by ACCESS_NETWORK_STATE
  app/src/main/AndroidManifest.xml
Labels: bug

#334 Fix audio player context not updated (#333)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#331 Implement the OAuth2 Device Authorization Grant
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/Credentials.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/DeviceAuthorizationResult.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthOptions.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/exception/ClientUnspecifiedException.kt
Labels: enhancement

#336 Add missing field at AttachmentMessage
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/AttachmentMessageRequest.kt
Labels: bug

#340 Provide thread factory used at executor (#339)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: enhancement

#347 Prevent focus loss between DM and TTS (#346)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: bug

#345 Modify access to the attahcment manager (#344)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
Labels: enhancement

#342 Support CallX directives for Display v1.2 (#341)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: enhancement

#350 Allow any speaker nullable (#349)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/SpeakerFactory.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#353 Remove hardcoded play context's priority (#352)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement
