Repository nugu-developers/nugu-android, pull requests merged in 2020-10, with the labels that each got.

#1269 Fix not to clear token during login #1261
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
Labels: fix

#1270 Fix thread synchronization issue in the backoff #1262
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/BackOff.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/BackOff.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/utils/BackOff.kt
Labels: fix

#1273 Add isExpired to NuguOAuth #1272
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: improve

#1275 Provide helper API to enable AudioPlayerAgent, LocationAgent #1274
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1271 Add ChromeWindow #1268
  nugu-ux-kit/build.gradle
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowBottomSheetBehavior.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
  nugu-ux-kit/src/main/res/drawable-xxxhdpi/view_chrome_window_dark_background.xml
  nugu-ux-kit/src/main/res/drawable-xxxhdpi/view_chrome_window_light_background.xml
  nugu-ux-kit/src/main/res/layout/bottom_sheet_chrome_window.xml
  nugu-ux-kit/src/main/res/values/strings.xml
  nugu-ux-kit/src/main/res/values/styles.xml
Labels: new

#1276 Fix wrong layout_behavior
  nugu-ux-kit/src/main/res/layout/bottom_sheet_chrome_window.xml
Labels: fix

#1278 Fix wrong calltimeout in Grpc(v1) and Http2 #1277
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/DeviceGatewayClient.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Call.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/FixedStateCall.kt
Labels: fix

#1281 Lock more finely #1280
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: improve

#1284 Fix wrong calltimeout in Grpc(v1) #1277
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
Labels: fix

#1283 Fix wrong context to MediaPlayerAgent
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Action.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Category.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Context.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/PlayerActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Playlist.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Song.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Target.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Toggle.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/User.kt
Labels: fix

#1287 Fix crash issue
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthCallbackActivity.kt
Labels: fix

#1289 Bugfix/issue 1286
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthCallbackActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: fix

#1293 Support PhoneCall v1.2 #1292
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
Labels: new

#1296 Add dialogRequestId param to onDiscoverableStart #1295
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt
Labels: improve

#1301 Support Message Interface v1.3 #1300
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Context.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/payload/SendCandidatesPayload.kt
Labels: improve

#1299 Support Chips Interface v1.1
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/Chip.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
Labels: improve

#1303 Fix the parameter of referrerDialogRequestId to dialogRequestId #1295
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
Labels: fix

#1305 Send full context for Prev,NextCommandIssued #1304
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1307 Cache AudioPlayer's context at init #1306
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1309 Prevent beep.play called twice. #1308
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
Labels: fix

#1311 Update SilverTray v4.2.6 #1310
  versions.gradle
Labels: improve

#1314 Update library #1313
  versions.gradle
Labels: improve

#1316 Prevent tts cancel from previous focus #1315
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1318 Support PhoneCall v1.2 #1317
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/MakeCallDirectiveHandler.kt
Labels: new

#1321 Prevent invalid holder focus acquisition #1320
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
Labels: improve

#1324 Fix tts's focus thread issue #1322
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: improve

#1325 Update the Authentication Token via accountByInAppBrowser method #1323
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/WebViewActivity.kt
Labels: improve

#1326 Implement exponentialBackOff #1213
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/ExponentialBackOff.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: improve

#1329 Replace android.util.log to LogInterface #1328
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/jademarble/EndPointDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/keensense/KeensenseKeywordDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/AudioSourceManager.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSource.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSourceFactory.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/helper/CustomTabsHelper.kt
Labels: improve

#1334 Fix wrong management for tts's playStack #1333
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSPlayContextProvider.kt
Labels: fix

#1337 Fix invalid clear for current param(attr) #1336
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1339 Send full context for RequestPlayCommand #1338
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlayCommandDirectiveHandler.kt
Labels: improve

#1332 Implement ThrottledOnClickListener
  app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateExtension.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ThrottledOnClickListener.kt
Labels: improve
