Repository nugu-developers/nugu-android, pull requests merged in 2020-11, with the labels that each got.

#1344 Support TTS Interface v1.3 #1343
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: new

#1345 Feature/issue 1341
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
Labels: new

#1347 Fix side-effect from issue-1320 #1346
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
Labels: fix

#1352 Revert issue-1320
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
Labels: fix

#1356 Add missing noti for directive failure #1355
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: fix

#1359 Improve warning notification #1358
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  app/src/main/res/values/strings.xml
Labels: improve

#1362 Update SilverTary v4.3.0 #1357
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
  versions.gradle
Labels: improve

#1361 Improve fallback of customTab #1360
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/helper/CustomTabActivityHelper.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/WebViewActivity.kt
Labels: fix

#1367 Deprecated System.UserInactivityReport #1366
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/SystemAgentInterface.kt
Labels: fix

#1365 Apply timer audioplayer's paused explicitly #1364
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1370 Fix wrong SONG spec in MediaPlayerAgent #136
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/Song.kt
Labels: fix

#1373 Apply cacheKey feature #1371
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/mediaplayer/MediaPlayerInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/IntegratedMediaPlayer.kt
Labels: improve

#1374 Support ASR v1.4 #1372
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
Labels: new

#1376 Update context timeout policy #1375
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
Labels: improve

#1378 Fix wrong param in MediaPlayerAgent #1377
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/NextDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/PreviousDirectiveHandler.kt
Labels: fix

#1380 Pre-cache Playstack context #1379
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
Labels: improve

#1383 Prevent seekTo for stopped source #1382
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1385 Prevent excessive mobile network usage in MediaPlayer #1384
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
Labels: fix

#1387 Prevent cancel already released object #1386
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
Labels: fix

#1389 Update Keensense v0.2.5 #1388
  versions.gradle
Labels: improve

#1392 Add exoplayer example for cache media #1391
  app/build.gradle
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  app/src/main/java/com/skt/nugu/sampleapp/player/SamplePlayerFactory.kt
  app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
  gradle.properties
Labels: enhancement

#1394 Replace dialogRequestId to header #1393
  app/src/main/java/com/skt/nugu/sampleapp/template/FragmentTemplateRenderer.kt
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerDisplayInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Labels: improve

#1396 Fix constant value to android.R.id.content #1395
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Labels: fix

#1399 Update session management #1398
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/session/SessionAgent.kt
Labels: improve

#1402 Change fields of epd param's as optional #1401
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
Labels: fix

#1407 Fix audioplayer's deadlock issue #1406
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1405 Fix not to pass outside touch event to child views in ChromeWindow #1404
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowBottomSheetBehavior.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowBottomSheetBehavior.kt
Labels: fix

#1414 Update backoff for gRPC #1349
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/PingService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/BackOff.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransport.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/PingService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/BackOff.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/PingService.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/utils/BackOff.kt
Labels: improve

#1413 Fix duplicate connections #1410
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/RegistryClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/RegistryClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
Labels: fix

#1418 Do not delay timer on player paused #1415
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1420 Update SilverTray v4.3.1 #1419
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer2.kt
  versions.gradle
Labels: improve

#1422 Add privacy url to nugu-service-kit #1421
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/Const.kt
Labels: fix

#1423 Add getGlobalVisibleRect method for control TouchEvent in App #1404
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
Labels: improve

#1425 Fix wrong directive result handling #1424
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/DirectiveGroupHandlingListener.kt
Labels: fix

#1428 Fix issue-1398 #1427
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/session/SessionAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
Labels: fix

#1431 Change wakeupInfo power parameter from mandatory to optional #1430
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: fix

#1433 Enable/Disable external lib log #1432
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/LogSettings.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
  versions.gradle
Labels: improve

#1434 Update AudioRecordSource for Android Q #1397
  nugu-android-helper/build.gradle
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/AudioSource.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSource.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSourceAboveQ.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/audiorecord/AudioRecordSourceFactory.kt
Labels: improve

#1435 Support Text Interface v1.5 #1403
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1438 Fix issue-1427 #1437
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
Labels: fix
