Repository nugu-developers/nugu-android, pull requests merged in 2020-01, with the labels that each got.

#161 Icon not exposed in AudioPlayer.Template (#160)
  app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
  app/src/main/res/layout/remote_views_music_player.xml
Labels: bug

#165 Move agent's factories to 'client-kit' package
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/ASRAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/AudioPlayerAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DelegationAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DisplayAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/ExtensionAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/LightAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/LocationAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/MicrophoneAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/MovementAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/SpeakerAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/SystemAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/TTSAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/TextAgentFactory.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultASRAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultAudioPlayerAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDelegationAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultDisplayAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultExtensionAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultLightAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultLocationAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultMicrophoneAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultMovementAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSpeakerAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultSystemAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTTSAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/impl/DefaultTextAgent.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/capability/asr/AbstractASRAgent.kt
Labels: enhancement

#169 Fix issue - new playSynchronizer (#164)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
Labels: bug

#170 Remove handling pause at display agent (#55)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/capabilityagents/display/DisplayAudioPlayerAgent.kt
Labels: bug, enhancement

#180 Remove exoplayer (#179)
  app/build.gradle
  app/src/main/java/com/skt/nugu/sampleapp/player/ExoMediaPlayer.kt
Labels: enhancement

#184 Allow playback button event at any state (#183)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#188 Improve timeUUID from v1 to v2 spec
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
Labels: enhancement

#195 Fix not notify audio player state changes (#194)
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#197 Fix isStartListeningWithTrigger flag (#196)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#199 Send referrerDialogRequestId (#198)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageInterpreter.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Header.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/AttachmentMessageRequest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/EventMessageRequest.kt
Labels: enhancement

#202 Divide resposibility for AbstractCapabilityAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractCapabilityAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AbstractASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AbstractAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/delegation/AbstractDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AbstractDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/extension/AbstractExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/light/AbstractLightAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/microphone/AbstractMicrophoneAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/movement/AbstractMovementAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/AbstractSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/AbstractTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/AbstractTTSAgent.kt
Labels: enhancement

#207 Fix protocols to HTTP_1_1 in RegistryClient
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
Labels: bug

#208 Add log to send message
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
Labels: enhancement

#210 Remove duplicate post
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
Labels: bug

#212 Fix issus for blocking at SDS'reader (#211)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/sds/CircularBufferSharedDataStream.kt
Labels: bug

#214 Issue v1.1 audio player command (#193)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
Labels: enhancement

#216 Add missing directive handler(mic) (#215)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
Labels: bug

#219 Prototype speaker interface v1.0 (#218)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/speaker/Speaker.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
Labels: enhancement

#220 Fix issue for SpeechRecognizerAg (#200)
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#222 Fix invalid payload event (#211)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
Labels: bug

#227 Fix display cleared while TTS speaking (#226)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug

#228 Discard visual focus management (#217)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AbstractDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/BaseDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAudioPlayerAgent.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
Labels: enhancement

#230 Fix issue when create SpeechRecognizerAg (#229)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#233 Unused code removal (#217)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AbstractDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/BaseDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAudioPlayerAgent.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
Labels: enhancement
