Repository nugu-developers/nugu-android, pull requests merged in 2020-06, with the labels that each got.

#754 Update gradle & plugin
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#751 Return getOffset in milliseconds (#750)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/util/TimeUnit.kt
Labels: enhancement

#748 Add callType at Person (#745)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
Labels: enhancement

#749 Apply client's os context (#747)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/OsContextProvider.kt
Labels: enhancement

#755 Update AudioPlayer v1.3
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#756 Fix build warnings
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowBottomSheetBehavior.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/ProgressTimer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/jademarble/EndPointDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speaker/AndroidAudioSpeaker.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/sds/CircularBufferSharedDataStream.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
Labels: enhancement

#757 Update SystemAgent v1.2
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
Labels: enhancement

#763 Adds templateId to sync player & template (#762)
  app/src/main/java/com/skt/nugu/sampleapp/service/MusicPlayerService.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerDirectivePreProcessor.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: enhancement

#765 Fix build error (#760)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/MakeCallDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
Labels: bug

#768 Fix publish error
  gradle.properties
Labels: bug

#767 Fix crash (#766)
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Directive.kt
Labels: bug, enhancement

#777 Fix missing connectionTimeout of Policy #776
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/devicegateway/DeviceGatewayClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/utils/ChannelBuilderUtils.kt
Labels: bug

#786 Fix SpeechRecognizerAggregator's issue (#785)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug, enhancement

#783 Manage audio focus for bluetooth streaming (#781)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothProvider.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#793 Update PhoneCall Interface v1.0 (#760)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Caller.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallClient.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/RecipientIntended.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
Labels: enhancement

#794 Use custom protobuf-javalite-3.10.0.jar (#775)
  nugu-client-kit/build.gradle
  nugu-client-kit/libs/protobuf-javalite-3.10.0.jar
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/MessageRequestConverter.kt
Labels: enhancement

#805 Fix missing protobuffer-javalite libs
  build.gradle
  nugu-client-kit/build.gradle
  nugu-client-kit/libs/protobuf-javalite-3.10.0.jar
Labels: bug

#806 Fix ConcurrentModificationException (#804)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: bug

#802 Feature/issue 801
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateFragment.kt
Labels: bug

#818 Add code to NuguOAuthError (#817)
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
  app/src/main/res/values/strings.xml
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/exception/BaseException.kt
Labels: enhancement

#821 Improve AbstractDirectiveHandler (#820)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractDirectiveHandler.kt
Labels: enhancement

#826 Update state of streaming & focus for BT (#825)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
Labels: bug

#831 Update ContactObject of MessageAgent (#827)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Contact.kt
Labels: enhancement

#834 Fix synchronization issue for LoopThread (#833)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/utils/LoopThread.kt
Labels: bug

#836 Fix the session not deactivated (#835)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#837 Add token for Caller object (#828)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Caller.kt
Labels: enhancement

#839 Fix invalid session timeout (#838)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
Labels: bug

#843 Update SilverTray v4.2.0 (#842)
  versions.gradle
Labels: enhancement

#840 Improve audio player's stop (#832)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#851 Fix JSONObject.get to JSONObject.optString (#848)
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
Labels: bug

#850 Implement NuguWebView (#824)
  nugu-service-kit/.gitignore
  nugu-service-kit/build.gradle
  nugu-service-kit/proguard-rules.pro
  nugu-service-kit/src/main/AndroidManifest.xml
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/WebViewUtils.kt
  settings.gradle
Labels: enhancement

#846 Support AudioPlayer v1.4 (845)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#854 Update SilverTray v4.2.1 (#853)
  versions.gradle
Labels: enhancement

#858 Update Chip by changing spec
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/Chip.kt
Labels: improve

#860 Remove unnecessary code from sampleApp (#856)
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoadingActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: fix

#866 Change calltype: CALL -> NORMAL (#865)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
Labels: improve
