Repository nugu-developers/nugu-android, pull requests merged in 2020-08, with the labels that each got.

#1031 Update gradle 4.0.1
  build.gradle
Labels: improve

#1033 Improve focus management #1032
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/Channel.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
Labels: improve

#1035 Update DialogUX's state immediately #1034
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: improve

#1038 Send missing StopRecognize event #1037
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: fix

#1042 Prevent calls when seek is not possible #1041
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1044 Add description for Display's render
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
Labels: improve

#1048 Improve focus & playSync management for tts #1043
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: improve

#1049 Add eventType to DisplayTemplate
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateExtension.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateModels.kt
  app/src/main/java/com/skt/nugu/sampleapp/template/TemplateViews.kt
Labels: improve

#1054 Add includeDialogAttribute flag #1053
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Labels: new

#1058 Send templateId for AudioPlayer correctly #1057
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1062 Clear dialog attribute before new tts start #1061
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1068 Fix wrong layer policy issue #1067
  nugu-core/src/main/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerImpl.kt
Labels: fix

#1066 Apply voice chrome policy changes (#1065)
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
Labels: improve

#1073 Apply Message Interface v1.2 #1072
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/Contact.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
Labels: new

#1071 Apply InteractionControl Message.GetMessage #1070
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/GetMessageDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/payload/GetMessagePayload.kt
Labels: new

#1077 Fix missing intent extras (#1076)
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthCallbackActivity.kt
Labels: fix

#1079 Rearrange focus priority (#1074)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
Labels: improve

#1082 Remove duplicate sessions at context #1081
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/session/SessionAgent.kt
Labels: fix

#1084 Use distinct for DialogRequestId,MessageId #1083
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1086 Implement TokenRefresher (#971)
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/TokenRefresher.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/MeResponse.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: improve

#1087 Bugfix/issue 1075
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1090 Return focus changes after tts stop #1089
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: improve

#1094 Fix acquireChannel for already active #1093
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/focus/FocusManagerTest.kt
Labels: fix

#1096 Immediately stop asr if possible #1095
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: improve

#1098 Fix not execute ASR.ExpectSpeech #1097
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1106 Fix wrong channel when request ASR by DM #1105
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1104 Change maximum number of texts in the chips (#1103)
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguChipsView.kt
Labels: improve

#1111 Fix not cancel ASR.ExpectSpeech from PlaySync#1110
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1109 Improve timeout logic in transport (#1107)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/Call.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/transport/FixedStateCall.kt
Labels: improve

#1115 Fix play called twice #1114
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1117 Fix incorrect error spec (#1116)
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
Labels: fix

#1119 Fix focus not release issue #1118
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
Labels: fix

#1120 Release focus of holder when no more need #1118
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
Labels: fix

#1122 Apply the flag to handle exception #1121
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/PlayStackManagerInterface.kt
Labels: fix

#1128 Fix invalidated release for FocusInteractor #1127
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
Labels: fix

#1132 Fix not start ASR after ASR.DM failed #1131
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1129 Enqueue callback not called
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/ChannelBuilderUtils.kt
Labels: fix

#1134 Fix invalid acquire focus at FocusHolder #1133
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSScenarioPlayer.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/SeamlessFocusManagerInterface.kt
Labels: fix

#1136 Tracking foreground channel correctly #1135
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
Labels: fix

#1139 Fix thread issue for asr callback #1138
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/SpeechRecognizeAttachmentSenderThread.kt
Labels: fix

#1144 Add cookie to NuguWebView in nugu-service-kit
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1148 Support PhoneCall 1.1 #1145
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Person.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/SendCandidatesDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayload.kt
  nugu-agent/src/test/java/com/nugu/sdk/agent/ext/phonecall/payload/SendCandidatesPayloadTest.kt
Labels: new

#1150 Return TTS's prehandle after finish current #1149
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: improve
