Repository nugu-developers/nugu-android, pull requests merged in 2020-04, with the labels that each got.

#554 Update AudioPlayer context always (#553)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: enhancement

#556 Fix exception for URI.create (#555)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#557 Implement sound agent
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/SoundProvider.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#559 Add User-Agent header
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
Labels: bug

#561 Update silvertray v4.1.14 (#560)
  versions.gradle
Labels: enhancement

#563 Fix display not cleared after back/forward (#562)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#565 Include full context for ElementSelected (#564)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ElementSelectedEventHandler.kt
Labels: enhancement

#568 Apply focus holder manager (#567)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogFocusHolderManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManagerImpl.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: enhancement

#570 Missing event when you receive a duplicate directive quickly in BluetoothAgent
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothAgentInterface.kt
Labels: bug

#572 Include wakeup.word if exist (#571)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: enhancement

#574 Fix beepName from string to enum (Sound Interface)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/SoundProvider.kt
Labels: bug

#577 Fix missing lyricsVisible (#576)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#581 Fix player not started somethimes (#580)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#583 Release resources when not used (#582)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#585 Add trigger callback (#584)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
Labels: enhancement

#587 Clear current item when playback completed (#586)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#592 Update current directive always (#590)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: bug, enhancement

#594 Cancel tts only if canceled by next tts (#593)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug, enhancement

#595 Unused code removal
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/mediaplayer/AndroidMediaPlayer.kt
Labels: enhancement

#597 Fix crash for eventStream (#596)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
Labels: bug

#598 Apply asr's timeout field for server EPD (#240)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/AsrRecognizeEventPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: enhancement

#600 Revert "Feature/issue 588"
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/AudioPlayerPlaybackInfoProvider.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
Labels: enhancement

#602 Clear display using sourceTemplateId (#601)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: bug

#604 Update silverTray v4.1.15
  versions.gradle
Labels: enhancement

#611 Fix wrong namespace for control events (#609)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlFocusDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlScrollDirectiveHandler.kt
Labels: bug

#613 Update agent version
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
Labels: enhancement

#606 Fix typos, remove unused file
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  app/src/main/java/com/skt/nugu/sampleapp/utils/SystemUtils.kt
  app/src/main/res/layout/activity_main.xml
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/bluetooth/BluetoothProvider.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/location/LocationProvider.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-ux-kit/src/main/res/drawable/round_snackbar_corners.xml
  nugu-ux-kit/src/main/res/values/colors.xml
Labels: bug

#614 Update agent version
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/AbstractSystemAgent.kt
Labels: enhancement

#616 Update jademarble v0.1.7 (#615)
  versions.gradle
Labels: enhancement

#620 Optimize receive message passing
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/EventStreamService.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageInterpreter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouterObserverInterface.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/NetworkManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/DirectiveMessage.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageConsumer.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/MessageObserver.kt
Labels: enhancement

#622 Stop called also after called (#621)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#623 Cleanup current item when released
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#625 Read directly at Attachment's reader (#624)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/RawCBRStreamSource.kt
Labels: enhancement

#626 Optimize read api to reduce cpu consume (#624)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt
Labels: enhancement

#630 Remove byte array copy (#627)
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/devicegateway/DeviceGatewayClient.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/message/request/AttachmentMessageRequest.kt
Labels: enhancement

#632 Prevent unintentional stopping of recognition (#631)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/FocusHolderManagerImpl.kt
Labels: bug

#637 Fix audio player not play after tts finished
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug

#636 Add dialogRequestId at ASR result listener (#635)
  app/src/main/java/com/skt/nugu/sampleapp/widget/BottomSheetController.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: enhancement

#639 Update silvertray v4.1.18
  versions.gradle
Labels: enhancement

#640 Cancel only matching directive
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: bug

#643 Optimize context build logic (#627)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: enhancement

#645 Fix wrong recognizer state changes (#644)
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: bug

#646 Update silvertray v4.1.19
  versions.gradle
Labels: enhancement

#647 Optimize context for compact format (#627)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultLocationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/DefaultBatteryAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackContextManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextManagerInterface.kt
Labels: bug, enhancement

#649 Add clientVersion to user-agent header
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/RegistryClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/utils/ChannelBuilderUtils.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/utils/UserAgent.kt
Labels: bug

#653 Fix wrong state value for context (#652)
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
Labels: bug, enhancement

#655 Skip ExpectSpeech handling
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug, enhancement

#651 Update display's state when changed (#627)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: enhancement

#656 Update silvertray v4.1.20
  versions.gradle
Labels: bug, enhancement

#658 Feature/optimize build context
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: enhancement

#659 Use setLength to resuse (#627)
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: enhancement

#662 Fix tts threading issue
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug, enhancement

#661 Deprecate timeoutInMillis at ExpectSpeech (#660)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: enhancement

#663 Ensure execution order for directive
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: bug

#665 Close session if occur error
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/SpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: bug, enhancement

#666 Determine behavior for resume btn
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug, enhancement

#667 Update tts's context always
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug, enhancement

#668 Prevent calling stop whenn already stop or finish
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: bug, enhancement

#670 Update battery context (#669)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/DefaultBatteryAgent.kt
Labels: bug, enhancement

#671 Fix - Remove test code
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: bug

#673 Fix expecting speech timing issue (#672)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  versions.gradle
Labels: bug

#675 Fix non-response for request (#674)
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/lyrics/AudioPlayerLyricsDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlayCommandDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/CloseDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlFocusDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlScrollDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ElementSelectedEventHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/playback/impl/PlaybackController.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/util/IgnoreErrorContextRequestor.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/context/ContextRequester.kt
Labels: enhancement

#676 Fix thread issue
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: bug

#679 Remove unused resource
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-hdpi/icn_chips.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-hdpi/nugu_btn_large_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-hdpi/nugu_btn_large_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-hdpi/nugu_btn_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-hdpi/nugu_btn_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-mdpi/icn_chips.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-mdpi/nugu_btn_large_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-mdpi/nugu_btn_large_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-mdpi/nugu_btn_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-mdpi/nugu_btn_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xhdpi/icn_chips.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xhdpi/nugu_btn_large_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xhdpi/nugu_btn_large_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xhdpi/nugu_btn_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xhdpi/nugu_btn_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxhdpi/icn_chips.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxhdpi/nugu_btn_large_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxhdpi/nugu_btn_large_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxhdpi/nugu_btn_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxhdpi/nugu_btn_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxxhdpi/icn_chips.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxxhdpi/nugu_btn_large_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxxhdpi/nugu_btn_large_nugu.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxxhdpi/nugu_btn_mic.png
  nugu-ux-kit/src/main/res/drawable-xhdpi/drawable-xxxhdpi/nugu_btn_nugu.png
Labels: bug
