Repository nugu-developers/nugu-android, pull requests merged in 2020-09, with the labels that each got.

#1155 Fix not stop requested on BUSY #1154
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: fix

#1159 Fix cookie naming convention from CamelCase to kebap-case #1158
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: fix

#1160 Improve oauth error handling in SampleApp #1142
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: improve

#1162 Add setTitle Javascript interface to NuguWebView (#1161)
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsAgreementActivity.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1164 Prevent tts from starting before handled. #1163
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/common/tts/TTSScenarioPlayer.kt
Labels: improve

#1166 Return handle of Play after focus finished. #1165
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: improve

#1172 Support Display Interface v1.6 #1171
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/RenderDirectiveHandler.kt
Labels: new

#1174 Feature/issue 1173
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1176 Fix not working stop trigger #1175
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: fix

#1179 Fix crash for v0.9.20 #1178
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
Labels: fix

#1181 Allow to change logger #1177
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
Labels: improve

#1183 Fix not return to idle state of DIalogUX #1182
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1189 Change endpoint URI #1184
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthCallbackActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
Labels: improve

#1196 Fix typo
  app/src/main/res/values/strings.xml
Labels: fix

#1191 Remove sessionId at ExpectSpeechPayload #1190
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
Labels: fix

#1193 Fix using wrong expectSpeechParam #1192
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1198 Allows to receive messages from any module #1197
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/SdkContainer.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/MessageDispatcher.kt
Labels: improve

#1200 Skip invalid value on build context #1199
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: fix

#1202 Add scope to OAuth #1169
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/Credentials.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: improve

#1204 Fix to run without login if token has not expired #1203
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
Labels: improve

#1208 Update libs #1207
  versions.gradle
Labels: improve

#1206 Add data field when requesting oauth #1205
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
Labels: improve

#1210 The display managed by rendering order. #1209
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
Labels: improve

#1212 Update SilverTray v4.2.5 #1211
  versions.gradle
Labels: improve

#1221 Fix missing state param for CSRF protection
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthCallbackActivity.kt
Labels: fix

#1223 Fix wrong logic to check if token has expired
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
Labels: fix

#1219 Fix wrong stop ExpectSpeech #1218
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1217 Do not manage focus at PhoneCallAgent #1216
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
Labels: improve

#1215 Fix missing EPD stop #1214
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
Labels: fix

#1228 Add beep directive delegate #1227
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/BeepDirective.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/BeepDirectiveDelegate.kt
  nugu-agent/src/test/java/com/nugu/sdk/agent/sound/BeepDirectiveParseTest.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1225 Add cacheMode method to NuguWebView
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1232 Fix audioplayer not working #1230
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1235 Prevent the issue of not calling onResponseStart #1234
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc/GrpcCall.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2Call.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Call.kt
Labels: improve

#1236 Delegate System.Exception directive #1233
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/ExceptionDirective.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/system/ExceptionDirectiveDelegate.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/agent/factory/DefaultAgentFactory.kt
Labels: fix

#1237 Revise log
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: improve

#1239 Prevent closing AudioSource while read #1185
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/audiosource/AudioSourceManager.kt
Labels: improve

#1241 Cancel focus when preHandled ASR.DM canceled #1240
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1243 Apply PlaySync for Display.Update directive #1242
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: improve

#1247 Apply focus for Sound(Beep) #1244
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
Labels: improve

#1246 Fix wrong ASR response timeout handling #1245
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
Labels: fix

#1249 Add AsrBeepPlayer #1248
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  app/src/main/java/com/skt/nugu/sampleapp/widget/ChromeWindowController.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepResourceProvider.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
Labels: new

#1251 Notify missing callback for startListening
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: improve

#1253 Fix side effect for #1242
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: fix

#1257 Change provideState() of SoundAgent #1256
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
Labels: fix

#1258 Initialize contextState before init block #1256
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSoundAgent.kt
Labels: fix

#1260 Return handle after focus requested #1259
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/SeamlessFocusManager.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/FocusManagerInterface.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/focus/SeamlessFocusManagerInterface.kt
Labels: fix

#1264 Call onFinish callback at first (hack) #1259
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
Labels: fix
