Repository nugu-developers/nugu-android, pull requests merged in 2021-09, with the labels that each got.

#2045 Change complete timing for Display.Close directive. #2044
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/CloseDirectiveHandler.kt
Labels: improve

#2053 Request focus always if bt playing #2052
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
Labels: improve

#2057 Remove Attachment's unused API #2056
  nugu-core/src/main/java/com/skt/nugu/sdk/core/attachment/StreamAttachment.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/attachment/Attachment.kt
Labels: improve

#2058 Test StreamAttachment
  nugu-core/src/test/java/com/skt/nugu/sdk/core/attachment/StreamAttachmentTest.kt
Labels: test

#2061 Remove unused class
  nugu-core/src/main/java/com/skt/nugu/sdk/core/utils/DequeSingleThreadExecutor.kt
Labels: improve

#2063 Fix lint warnings
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/Credentials.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthError.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthOptions.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/helper/CustomTabActivityHelper.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/helper/CustomTabsHelper.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/net/Headers.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/utils/PackageUtils.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
Labels: fix

#2071 Test ContextManager
  nugu-core/src/test/java/com/skt/nugu/sdk/core/context/ContextManagerTest.kt
Labels: test

#2075 Add test code to grpc transport
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransport.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/RegistryClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/GsonUtils.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/Grpc2CallTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransportFactoryTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransportTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/NuguServerInfoTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/PolicyTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/RegistryClientTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/TransportStateTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClientTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsServiceTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/AddressTest.kt
  nugu-client-kit/src/test/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/ChannelBuilderUtilsTest.kt
Labels: test

#2078 Fix side effect for #2001 #2077
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix
