Repository nugu-developers/nugu-android, pull requests merged in 2021-04, with the labels that each got.

#1688 Add close button to display templater
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
Labels: enhancement

#1689 Fix test error
  nugu-agent/src/test/java/com/skt/nugu/sdk/agent/playbackcontrol/PlaybackControllerTest.kt
Labels: fix

#1699 Create test_PR.yml
  .github/workflows/test_PR.yml
Labels: improve

#1695 Apply mobile VoiceChrome spec
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowBottomSheetBehavior.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
Labels: bug

#1704 Write test for LocationAgent #1703
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/location/LocationAgent.kt
  nugu-agent/src/test/java/com/skt/nugu/sdk/agent/location/LocationAgentTest.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: test

#1707 Fix memory leak when orientation changed
  app/src/main/java/com/skt/nugu/sampleapp/utils/PreferenceHelper.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguVoiceChromeView.kt
Labels: bug

#1712 Setup build environment
  build.gradle
  versions.gradle
Labels: improve

#1720 Fix crash
  app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingHeadWindow.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
Labels: fix

#1727 Cast string -> boolean
  build.gradle
Labels: fix

#1730 Fix AudioPlayer's focus not canceled #1729
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1733 Update libs
  app/build.gradle
  build.gradle
  nugu-agent/build.gradle
  nugu-android-helper/build.gradle
  nugu-client-kit/build.gradle
  nugu-client-transport-http2/build.gradle
  nugu-core/build.gradle
  nugu-login-kit/build.gradle
  nugu-service-kit/build.gradle
  nugu-ux-kit/build.gradle
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowBottomSheetBehavior.kt
  versions.gradle
Labels: improve

#1732 Fix wrong focus release #1731
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
Labels: fix

#1739 Add Speaking Target at Chips #1738
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/RenderDirective.kt
Labels: new

#1737 Support ASR Interface v1.6
  app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingHeadWindow.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ExpectSpeechPayload.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Labels: new

#1742 Remove unused code
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ElementSelectedEventHandler.kt
Labels: improve

#1745 Cancel continue if paused by another request #1744
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: improve

#1751 Enable/Disable deepLink in WebViewActivity #1750
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/WebViewActivity.kt
Labels: improve

#1754 Deliver chips, target LISTEN or SPEAKING #1753
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#1757 Notify dialogMode changes #1756
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: improve

#1755 Add test case for nugu-login-kit #1743
  nugu-login-kit/build.gradle
  nugu-login-kit/src/androidTest/java/com/skt/nugu/sdk/platform/android/login/ExampleInstrumentedTest.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/ExampleUnitTest.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/CredentialsTest.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthErrorTest.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthTest.kt
Labels: test

#1758 Ensure preHandle of all directives's handle #591
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveGroupProcessor.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveSequencer.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/directive/DirectiveSequencerInterface.kt
Labels: improve

#1760 Add listener for PlaySynchronizer #1759
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizer.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/playsynchronizer/PlaySynchronizerTest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/playsynchronizer/PlaySynchronizerInterface.kt
Labels: improve

#1771 Not stop play synced when routine stopped #1770
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: improve

#1773 Feature/issue 1770
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: improve

#1775 Fix wrong play stack order #1774
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/PlayStackProvider.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/playstack/PlayStackManagerTest.kt
Labels: fix

#1776 Test PlayStackManager #1774
  nugu-core/src/test/java/com/skt/nugu/sdk/core/playstack/PlayStackManagerTest.kt
Labels: improve

#1778 Stop ASR after chips clicked #1777
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
Labels: improve

#1780 Clear chips at IDLE state #1779
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#1788 Add listener for Session #1787
  nugu-core/src/main/java/com/skt/nugu/sdk/core/session/SessionManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/session/SessionManagerTest.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/session/SessionManagerInterface.kt
Labels: improve

#1792 Notify dialogMode changed only if speaking #1791
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#1790 Clear chips explicitly #1789
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/handler/RenderDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: fix

#1796 Update JadeMarble v0.2.6 #1795
  versions.gradle
Labels: fix

#1798 Add start API for Routine #1797
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
Labels: new

#1799 Fix typo #1789
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/handler/RenderDirectiveHandler.kt
Labels: fix

#1800 Test InteractionControlManager
  nugu-core/src/test/java/com/skt/nugu/sdk/core/interaction/InteractionControlManagerTest.kt
Labels: test

#1802 Bugfix/issue 1801
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: fix

#1804 Test DialogAttributeStorage
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/dialogattribute/DialogAttributeStorage.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/dialogattribute/DialogAttributeStorageTest.kt
Labels: test

#1806 Test InterLayerDisplayPolicyManager
  nugu-core/src/main/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerImpl.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/display/InterLayerDisplayPolicyManagerTest.kt
Labels: test

#1807 Test InputProcessor
  nugu-core/src/main/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManager.kt
  nugu-core/src/test/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManagerTest.kt
Labels: test
