Repository nugu-developers/nugu-android, pull requests merged in 2021-11, with the labels that each got.

#2118 Add parentTemplateId param at render() #2117
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregator.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAggregatorInterface.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
Labels: new

#2120 Remove javax annotation dependency
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-core/build.gradle
Labels: improve

#2125 Improve nugu-login-kit
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClient.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthClientTest.kt
  nugu-login-kit/src/test/java/com/skt/nugu/sdk/platform/android/login/net/HttpClientTest.kt
Labels: improve

#2130 Reduce test failure
  nugu-core/src/test/java/com/skt/nugu/sdk/core/inputprocessor/InputProcessorManagerTest.kt
Labels: improve

#2131 Expand access modifier on TemplateHandler, TemplateRenderer for easier customizing
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/DefaultTemplateHandler.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateAndroidHandler.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateHandler.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateMediaHandler.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/controller/TemplateNuguHandler.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
Labels: improve

#2136 Build apple silicon
  nugu-client-kit/build.gradle
Labels: improve

#2137 Fix build warning
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultClientSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/impl/DefaultServerSpeechRecognizer.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/playback/impl/PlaybackCommand.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/playback/impl/PlaybackMessageRequest.kt
  nugu-android-helper/build.gradle
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/keensense/KeensenseKeywordDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
Labels: improve

#2139 Fix side-effect for #2134
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/channel/DefaultFocusChannel.kt
Labels: fix

#2140 Add debug log
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: improve

#2143 Refactor context manager
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: improve

#2149 Change coloring logic on LyricsView for making it easy to custom it
  app/src/main/java/com/skt/nugu/sampleapp/activity/main/CustomMediaTemplate.kt
  app/src/main/res/layout/custom_media_player.xml
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/MediaTemplateResources.kt
  nugu-ux-kit/src/main/res/drawable/nugu_album_cover_bg.xml
  nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
  nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml
  nugu-ux-kit/src/main/res/layout/view_lyrics.xml
  nugu-ux-kit/src/main/res/layout/view_music_bar_player.xml
  nugu-ux-kit/src/main/res/values/colors.xml
  nugu-ux-kit/src/main/res/values/styles.xml
Labels: improve

#2153 Public EndCallPayload's member #2152
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/payload/EndCallPayload.kt
Labels: fix

#2154 Fix typo
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/MessageAgentInterface.kt
Labels: fix
