Repository nugu-developers/nugu-android, pull requests merged in 2021-05, with the labels that each got.

#1815 Fix missing call directive complete #1814
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: fix

#1819 Fix crash #1818
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: fix

#1817 Fix MediaTemplate layout malfunction #1816
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/TemplateNativeView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
  nugu-ux-kit/src/main/res/layout/view_display_audioplayer_land.xml
  nugu-ux-kit/src/main/res/layout/view_display_audioplayer_port.xml
Labels: fix

#1822 Add force parameter to TokenRefresher.start in sampleApp #1821
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/TokenRefresher.kt
Labels: fix

#1825 SetComplete ASR.ExpectSpeech after ASR #1824
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1828 Precache context at build NuguClient #1827
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultBluetoothAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/permission/PermissionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/SoundAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/utility/UtilityAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/playstack/PlayStackContextManager.kt
Labels: improve

#1837 Fix invalid result handling for TTS.Speak #1836
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1841 SetComplete when preHandleDirective canceled #1840
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/AbstractDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1844 Add removeJsonNull extension function
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/util/GsonUtils.kt
  nugu-agent/src/test/java/com/skt/nugu/sdk/agent/util/GsonUtilsTest.kt
Labels: new

#1848 Improve ExoMediaPlayer
  app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
Labels: improve

#1853 Revert "Clear chips at IDLE state #1779"
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
Labels: fix

#1861 Fix ConcurrentModificationException #1860
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: fix

#1870 Send full cnxt for CandidatesListed event #1869
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendCandidatesDirectiveHandler.kt
Labels: improve

#1873 Prevent back to IDLE if TTS prepaing #1872
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1878 Fix missing initiator at context #1877
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1882 Add routine javascript Interface to NuguWebView #1880
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavaScriptHelper.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1885 Add api to get routine's state #1884
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
Labels: new

#1883 Create new player
  app/src/main/java/com/skt/nugu/sampleapp/player/SamplePlayerFactory.kt
Labels: fix

#1889 Update voiceChrome policy #1862
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Labels: improve
