Repository nugu-developers/nugu-android, pull requests merged in 2021-10, with the labels that each got.

#2096 Remove unused imports
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDelegationAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ElementSelectedEventHandler.kt
Labels: improve

#2087 Apply Nudge Chips Policy #2086
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/asr/ASRAgentInterface.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/dialog/DialogUXStateAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/beep/AsrBeepPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
Labels: new

#2098 Change triggerChild API spec #2082
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgentInterface.kt
Labels: improve

#2102 Fix wrong parameter and remove unnecessary test code
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/test/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragmentTest.kt
Labels: fix
