Repository nugu-developers/nugu-android, pull requests merged in 2021-08, with the labels that each got.

#1998 Fix NuguButton not to be disabled according to NUGU UX policy
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
Labels: fix

#2002 Reset tts player if need #2001
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
Labels: fix

#1997 Pause AudioPlayer explicitly #1996
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidAudioFocusInteractor.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/focus/AndroidContextDummyFocusInteractorFactory.kt
Labels: improve

#2009 Add interface to control routine's directive #2008
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/handler/ContinueDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/handler/StartDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgentInterface.kt
Labels: new

#2012 Remove unused empty callback #2011
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultExtensionAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultMicrophoneAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultScreenAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSpeakerAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultSystemAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/lyrics/AudioPlayerLyricsDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlayCommandDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/CloseDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/ControlFocusDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/GetInfoDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/HandleLyricsDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/HandlePlaylistDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/MoveDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/NextDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/PauseDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/PlayDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/PreviousDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/ResumeDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/RewindDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/SearchDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/StopDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/mediaplayer/handler/ToggleDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/ReadMessageDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/message/handler/SendMessageDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/handler/MakeCallDirectiveHandler.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/sound/SoundAgent.kt
Labels: improve

#2019 Remove ogg-opus encoder (temporary) #2018
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/EndianUtils.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/JNAOpus.java
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OggCrc.java
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OggOpusEncoder.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OggOpusWriter.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OggPageHeader.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OpusHeader.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/opus/OpusTags.kt
  nugu-android-helper/src/main/jniLibs/arm64-v8a/libjnidispatch.so
  nugu-android-helper/src/main/jniLibs/arm64-v8a/libopus.so
  nugu-android-helper/src/main/jniLibs/armeabi-v7a/libjnidispatch.so
  nugu-android-helper/src/main/jniLibs/armeabi-v7a/libopus.so
  nugu-android-helper/src/main/jniLibs/armeabi/libjnidispatch.so
  nugu-android-helper/src/main/jniLibs/armeabi/libopus.so
  nugu-android-helper/src/main/jniLibs/x86/libjnidispatch.so
  nugu-android-helper/src/main/jniLibs/x86/libopus.so
  nugu-android-helper/src/main/jniLibs/x86_64/libjnidispatch.so
  nugu-android-helper/src/main/jniLibs/x86_64/libogg.so
  nugu-android-helper/src/main/jniLibs/x86_64/liboggopus.so
  nugu-android-helper/src/main/jniLibs/x86_64/libopus.so
  nugu-android-helper/src/main/jniLibs/x86_64/libspeex.so
  nugu-android-helper/src/main/jniLibs/x86_64/libspeexdsp.so
Labels: new

#2023 Fix ExoMediaPlayer(Sample) cacheKey update order (COSTELTV-76)
  app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
Labels: fix

#2021 Apply logic that restore previous render info on webView media template.
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
Labels: fix

#2025 Use asset resource directly #2024
  app/build.gradle
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/jademarble/EndPointDetector.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/keensense/KeensenseKeywordDetector.kt
  versions.gradle
Labels: improve

#2037 Add format type at requestTTS #2036
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/tts/TTSAgentInterface.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/ClientHelperInterface.kt
Labels: improve
