Repository nugu-developers/nugu-android, pull requests merged in 2021-01, with the labels that each got.

#1503 Fix memory leak in SampleApp
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
Labels: fix

#1498 Change Date().time to System.currentTimeMillis() #1497
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/utils/UUIDGeneration.kt
Labels: fix

#1501 Update grpc v1.34.0 #1500
  app/build.gradle
  build.gradle
  nugu-client-kit/build.gradle
  nugu-client-transport-http2/build.gradle
  nugu-core/build.gradle
  nugu-service-kit/build.gradle
  nugu-ux-kit/build.gradle
Labels: improve

#1499 Support nugu configuration #1330
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skt/nugu/sampleapp/activity/IntroActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsAgreementActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  app/src/main/res/values/strings.xml
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/configuration/ConfigurationStoreExtension.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/configuration/Configuration.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/configuration/ConfigurationMetadata.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/configuration/ConfigurationStore.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/GrpcTransport.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/NuguServerInfo.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/RegistryClient.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/HTTP2Transport.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/NuguServerInfo.kt
  nugu-client-transport-http2/src/main/java/com/skt/nugu/sdk/client/port/transport/http2/RegistryClient.kt
  nugu-login-kit/build.gradle
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: new

#1512 Send full context for ListenTimeout #1511
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: new

#1517 Replace ChromeWindowController to ChromeWindow
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_sheet_voice_window.xml
Labels: improve

#1514 Add Custom TemplateView Constructor
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
Labels: improve

#1518 Add theme setting method to NuguOAuth #1441
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
Labels: improve

#1523 Send full context at Request***CommandIssued #1522
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/audioplayer/playback/AudioPlayerRequestPlaybackCommandDirectiveHandler.kt
Labels: improve

#1529 Pass EPD model file path instead of EPD #1528
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: improve

#1532 Fix timeout exception handling #1531
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1538 Add missing listener registration #1537
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTTSAgent.kt
Labels: fix

#1536 Fix not working focus manager #1535
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
Labels: fix

#1542 Fix bug about when Nugu Button has to be shown or not.
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
Labels: fix

#1545 Fix not playing audio player sometimes #1544
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1549 Fix missing audio stream release #1548
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1547 Apply interaction control at TextRedirect #1546
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultTextAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
Labels: new

#1551 Simplify snapshot build #1550
  build.gradle
  publish-android.gradle
  publish.gradle
  versions.gradle
Labels: improve

#1552 Fix not playing or stopping sometimes #1544
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1554 Fix not release playSync #1553
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: fix

#1558 Handle multiple displayCardRendered call #1557
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: improve

#1556 Change method naming of NuguOAuth #1539
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/client/TokenRefresher.kt
  app/src/main/res/layout/activity_login.xml
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthOptions.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/NuguOAuthCallbackActivity.kt
Labels: improve

#1559 Type timestamp by hand #1550
  build.gradle
  versions.gradle
Labels: fix
