Repository nugu-developers/nugu-android, pull requests merged in 2021-03, with the labels that each got.

#1608 Support Display v1.7 #1607
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultDisplayAgent.kt
Labels: new

#1610 Support AudioPlayer v1.6 #1609
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: new

#1612 Improve getContext API #1611
  nugu-core/src/main/java/com/skt/nugu/sdk/core/context/ContextManager.kt
Labels: improve

#1615 Add annotations-api for Java 9+.
  nugu-client-kit/build.gradle
Labels: improve

#1618 Ignore external audio focus result #1617
  nugu-core/src/main/java/com/skt/nugu/sdk/core/focus/FocusManager.kt
Labels: fix

#1622 Remove unused dependencies in sampleApp #1621
  app/build.gradle
Labels: fix

#1629 Add deviceUniqueId to NuguWebView #1628
  app/src/main/java/com/skt/nugu/sampleapp/activity/SettingsServiceActivity.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: improve

#1631 Improve gRPC connection for backoff and reconnect #1627
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DeviceGatewayTransport.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/DirectivesService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/EventsService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/devicegateway/PingService.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/grpc2/utils/BackOff.kt
Labels: improve

#1636 Fix incorrectly cancel for the action #1635
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: fix

#1637 Move default transportFactory from ClientManager to NuguAndroidClient #1632
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/NuguAndroidClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/NuguClient.kt
  nugu-client-kit/src/main/java/com/skt/nugu/sdk/client/port/transport/DefaultTransportFactory.kt
  nugu-interface/src/main/java/com/skt/nugu/sdk/core/interfaces/auth/AuthDelegate.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
Labels: improve

#1638 Update IntroActivity #1598
  app/src/main/java/com/skt/nugu/sampleapp/activity/IntroActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/LoginActivity.kt
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
Labels: improve

#1642 Change the updateChips method to public. #1641
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
Labels: improve

#1640 Support Chips Interface v1.2 #1583
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/ChipsAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/chips/RenderDirective.kt
Labels: new

#1644 Add isChipsEmpty method in ChromeWindow #1641
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindow.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/ChromeWindowContentLayout.kt
Labels: improve

#1649 Apply blocking policy for AudioPlayerHandler #1648
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/AudioPlayerTemplateHandler.kt
Labels: fix

#1655 Embed epd, keyword resources at sample app #1639
  app/build.gradle
  app/src/main/java/com/skt/nugu/sampleapp/client/ClientManager.kt
Labels: improve

#1654 Add getOptions method in NuguOAuth #1653
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuth.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/auth/NuguOAuthInterface.kt
Labels: improve

#1658 Fix bug that close button not work when fragment reused
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
Labels: bug

#1659 Fix qa issue(NUGUSDKQA-46)
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
Labels: bug

#1665 Rename setCookie to addCookie in NuguWebView
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/NuguWebView.kt
Labels: fix

#1669 Fix routine canceled incorrectly #1668
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
Labels: fix

#1671 Apply blocking policy for RequestPermission #1670
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/permission/RequestPermissionDirectiveHandler.kt
  nugu-agent/src/test/java/com/skt/nugu/sdk/agent/permission/RequestPermissionDirectiveHandlerTest.kt
Labels: improve

#1675 Improve TriggerCallback #1674
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregatorInterface.kt
Labels: improve

#1681 Fix SpeechRecognzier invalid operation #1680
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechProcessorDelegate.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/platform/android/speechrecognizer/SpeechRecognizerAggregator.kt
Labels: fix

#1685 Update dokka 0.10.0 -> 1.4.30 #1684
  build.gradle
  javadoc-android.gradle
  javadoc.gradle
Labels: improve
