Repository nugu-developers/nugu-android, pull requests merged in 2021-06, with the labels that each got.

#1890 Support Battery Interface 1.1 #1865
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/BatteryStatusProvider.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/battery/DefaultBatteryAgent.kt
Labels: new

#1895 Update SilverTray v4.3.4 #1894
  nugu-android-helper/build.gradle
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer.kt
  nugu-android-helper/src/main/java/com/skt/nugu/sdk/external/silvertray/NuguOpusPlayer2.kt
  versions.gradle
Labels: improve

#1892 Apply version diversity to js function call.
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
Labels: improve

#1898 Update SilverTray v4.3.6 #1897
  versions.gradle
Labels: improve

#1902 Test JavaScriptHelper
  nugu-service-kit/src/androidTest/java/com/skt/nugu/sdk/platform/android/service/webkit/JavaScriptHelperTest.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavaScriptHelper.kt
Labels: test

#1903 Test JavascriptObjectReceiver
  nugu-service-kit/src/androidTest/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiverTest.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/JavascriptObjectReceiver.kt
Labels: test

#1904 Add log to track issue AISTBQA-4648
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/display/DisplayAgent.kt
  nugu-core/src/main/java/com/skt/nugu/sdk/core/directivesequencer/DirectiveProcessor.kt
Labels: improve

#1906 Fix cancel ExpectSpeech when stopRecognition #1905
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultASRAgent.kt
Labels: fix

#1908 Refactor NuguErrorExtentions in SampleApp
  app/src/main/java/com/skt/nugu/sampleapp/client/NuguErrorExtentions.kt
Labels: fix

#1912 Add api to get context for Routine #1911
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgent.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/routine/RoutineAgentInterface.kt
Labels: new

#1923 Add template onStart() call back to Listener
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
Labels: improve

#1927 Prevent call requestPermission on permission deny
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
Labels: fix

#1930 Fix missing initialized
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/ServerInitiatedDirectiveController.kt
Labels: fix

#1938 Add the way App can custom close button of TemplateView
  app/src/main/java/com/skt/nugu/sampleapp/activity/MainActivity.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/TemplateView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
Labels: improve

#1947 Fix to notify status when disable is called
  nugu-core/src/main/java/com/skt/nugu/sdk/core/network/MessageRouter.kt
Labels: fix
