Repository nugu-developers/nugu-android, pull requests merged in 2021-12, with the labels that each got.

#2165 Fix side effect for #2159
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/text/TextAgent.kt
Labels: fix

#2163 Update ExoPlayer
  app/src/main/java/com/skt/nugu/sampleapp/player/exo/ExoMediaPlayer.kt
  versions.gradle
Labels: enhancement

#2170 Support PhoneCall v1.3 #2169
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/Context.kt
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/ext/phonecall/PhoneCallAgent.kt
Labels: new
