Repository nugu-developers/nugu-android, pull requests merged in 2023-01, with the labels that each got.

#2349 Fix weird fast scrolling when dragging first item on playlist.
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
  nugu-ux-kit/src/main/res/layout/nugu_fragment_playlist.xml
Labels: fix

#2354 Append playServiceId at ModifyPlaylist event payload
  nugu-agent/src/main/java/com/skt/nugu/sdk/agent/DefaultAudioPlayerAgent.kt
Labels: new

#2355 Fix title issue and avoid crash
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
Labels: fix

#2360 Add textinput event type handling of Button
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateRenderer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistInterface.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
Labels: fix

#2361 Fix issue that replaced list is not applied.
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
Labels: fix

#2359 Update Compile & Target sdk 33 #2358
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/skt/nugu/sampleapp/service/floating/FloatingView.kt
  nugu-login-kit/src/main/java/com/skt/nugu/sdk/platform/android/login/view/WebViewActivity.kt
  nugu-service-kit/src/main/java/com/skt/nugu/sdk/platform/android/service/webkit/WebViewUtils.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/webview/TemplateWebView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguButton.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguFloatingActionButton.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/NuguVoiceChromeView.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/widget/VoiceChromeView.kt
  versions.gradle
Labels: improve

#2362 Change PlaylistRenderer access modifier for customize layout
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/DisplayAudioPlayer.kt
Labels: improve

#2364 Fix issue Delete button enable state not updated after deletion
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistViewModel.kt
Labels: fix

#2365 Fix issue that notifyRenderFailed() invoked when TemplateFragment is …
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/presenter/TemplateFragment.kt
Labels: fix

#2366 Add lyrics view layout attribute on LyricView for customizing
  app/src/main/res/layout/custom_media_player.xml
  app/src/main/res/layout/view_custom_item_lyrics.xml
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/LyricsView.kt
  nugu-ux-kit/src/main/res/values/styles.xml
Labels: improve

#2367 Scroll to current playing position on Playlist
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistAdapter.kt
  nugu-ux-kit/src/main/java/com/skt/nugu/sdk/platform/android/ux/template/view/media/playlist/PlaylistFragment.kt
Labels: improve

#2368 Fix Playlist GUI issue
  nugu-ux-kit/src/main/res/layout/nugu_fragment_playlist.xml
Labels: fix
